
services:
  db:
    container_name: dd-database
    image: postgres:latest
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init_scripts:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U dd_user -d dd_database'"]
      interval: 5s
      timeout: 3s
      retries: 3
      
  user-bot:
    container_name: dd-user-bot
    build:
      context: user-bot/
    env_file:
      - database/.db.env
    restart: always
    depends_on:
      db:
        condition: service_healthy
      
  staff-bot:
    container_name: dd-staff-bot
    build:
      context: staff-bot/
    env_file:
      - database/.db.env
    restart: always
    depends_on:
      db:
        condition: service_healthy
